name: MLops Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

# No repositório MLops
jobs:
  job-treino:
    uses: LEONARDODF/Include-repo/.github/workflows/train-python.yml@main

  job-docker:
    needs: job-treino  # AQUI é o lugar certo do 'needs'
    uses: LEONARDODF/Include-repo/.github/workflows/build-docker.yml@main